#+title: Authenticate Printer

* Introduction

A simple C client that authenticates to a printer server using CUPS.
It makes use of the following library: [[https://github.com/pieterhijma/authenticate-printer-library][authenticate-printer-library]].

* Prerequisites

- A C compiler
- Make
- CUPS

In some distributions the CUPS header files are in a package ~libcups2-dev

* Compilation

First we clone the git submodule for the authenticate-printer-library
from the root of this project:

#+begin_src sh
git submodule init
git submodule update
#+end_src

We then compile the authenticate-printer-library:

#+begin_src sh
cd authenticate-printer-library
make
cd ..
#+end_src

We then compile the client:

#+begin_src sh
make
#+end_src

* Running

To run the client, it is necessary to ensure that the system can find
the shared library.  For example, add to environment variable
LD_LIBRARY_PATH the path to the shared library and store it in a shell
initialization script, for example ~.bashrc~:

#+begin_src sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/authenticate-printer/authenticate-printer-library
#+end_src

We can then run the program with:

#+begin_src sh
./authenticate-printer
#+end_src
* Typical usage

Typical usage is the following: First check whether the file is in A4
format:

#+begin_src sh
pdfinfo file.pdf
#+end_src

If it is, we can check whether the printer is available with:

#+begin_src sh
lpq
#+end_src

We then send the file to the printer:

#+begin_src sh
lpr file.pdf
#+end_src

We then check whether the file is done processing.  This is the case
when the file jumps from rank "active" to rank "1st":

#+begin_src sh
lpq +5
#+end_src

With output something similar to:

#+begin_example
myprinter is ready and printing
Rank    Owner   Job     File(s)                         Total Size
active  pieter  331     file.pdf                        151552 bytes
myprinter is ready
Rank    Owner   Job     File(s)                         Total Size
1st     pieter  331     file.pdf                        151552 bytes
#+end_example

At this point, we can authenticate the printer for multiple jobs with:

#+begin_src sh
./authenticate-printer
#+end_src

We can then verify that the rank changes to "active" again with:

#+begin_src sh
lpq +5
#+end_src

The program will exit when all documents have been processed.

